/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get platform status
         * @description Returns the health of public Galileo services. Authentication is optional.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current account
         * @description Verifies the API key and returns identity, credits, tier, and account limits.
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List available models
         * @description Returns the models and concrete builds offered by this deployment.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current quota
         * @description Returns the current sliding-window state for each metered operation.
         */
        get: operations["getQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get credit balance and pricing
         * @description Returns the account balance and the rate card used for evaluation pricing.
         */
        get: operations["getCredits"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List evaluations
         * @description Returns the caller's evaluations, newest first.
         */
        get: operations["listEvaluations"];
        put?: never;
        /**
         * Create an evaluation
         * @description Queues a video for analysis and returns immediately. The response starts
         *     in `queued` state. Retrieve it by ID until it reaches a terminal state.
         *
         *     The video may be at most 15 seconds and 50 MB, H.264/AVC in an MP4
         *     container. The request body itself is capped at 2 MB, which only binds on
         *     `b64_json` -- see `VideoRef`.
         */
        post: operations["createEvaluation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Evaluation identifier. */
                evaluation_id: components["parameters"]["EvaluationId"];
            };
            cookie?: never;
        };
        /**
         * Retrieve an evaluation
         * @description Returns the current job status and its result when available.
         */
        get: operations["retrieveEvaluation"];
        put?: never;
        post?: never;
        /**
         * Delete an evaluation
         * @description Deletes an evaluation owned by the caller.
         */
        delete: operations["deleteEvaluation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve an upload
         * @description First of the three calls that upload a video. Returns an `upload_path`
         *     to send the bytes to, and the `video_id` you will reference from an
         *     evaluation.
         *
         *     The whole sequence:
         *
         *     1. `POST /v1/videos` with the file's content type and size. You get back
         *        a `video_id` and a short-lived `upload_path`.
         *     2. `PUT` the raw bytes to `upload_path`. **Send no `Authorization`
         *        header on this request** -- `upload_path` is on separate storage
         *        infrastructure, not this API, and a key sent there is a key
         *        disclosed to a third party. Declare `Content-Length`; a request that
         *        does not is refused. The grant expires after 15 minutes, and a
         *        replacement means starting again at step 1.
         *     3. `POST /v1/videos/{video_id}/complete`, which hands the file to
         *        validation. Poll `GET /v1/videos/{video_id}` until `status` is
         *        `ready`; only then may an evaluation reference it.
         *
         *     Pass `content_hash` (SHA-256 of the bytes, hex) to skip the transfer
         *     when we already hold that exact content: the response then carries
         *     `skip_upload: true` and no `upload_path`, and the video is immediately
         *     usable. Nothing is charged for the bytes you did not send.
         *
         *     This consumes an `upload` quota slot. A rejected content type or an
         *     oversized `size_bytes` is refused before the slot is taken.
         */
        post: operations["createVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos/{video_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Video identifier, as returned by `POST /v1/videos`. */
                video_id: components["parameters"]["VideoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish an upload
         * @description Third of the three calls. Declares that the bytes have landed and hands
         *     the file to validation, which checks the container and codec (H.264/AVC
         *     in MP4) and the duration.
         *
         *     Validation is asynchronous: the status returned here is normally
         *     `processing`. Poll `GET /v1/videos/{video_id}` for the outcome. Calling
         *     this on a video that is already `ready` or `failed` is harmless and
         *     changes nothing.
         */
        post: operations["completeVideo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/videos/{video_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Video identifier, as returned by `POST /v1/videos`. */
                video_id: components["parameters"]["VideoId"];
            };
            cookie?: never;
        };
        /**
         * Retrieve a video
         * @description Returns the stored record and its validation status. `ready` means an evaluation may reference it. `failed` means validation rejected the file -- the container, the codec or the duration -- and carries no further detail today, so re-check the file against the limits on `POST /v1/evaluations` rather than expecting a reason here.
         */
        get: operations["retrieveVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @default galileo
         * @enum {string}
         */
        ModelId: "galileo" | "gemini";
        /** @enum {string} */
        GlitchType: "visual_glitch" | "prompt_misalignment";
        /** @enum {string} */
        EvaluationStatus: "queued" | "processing" | "completed" | "partial" | "failed";
        /** @enum {string} */
        DetectorStatus: "pending" | "reused" | "completed" | "failed" | "skipped";
        /** @enum {string} */
        VideoStatus: "pending" | "processing" | "ready" | "failed";
        VideoCreate: {
            /**
             * @description Only MP4 is accepted.
             * @enum {string}
             */
            content_type: "video/mp4";
            /** @description Exact size of the file you are about to send. It is signed into the grant, so the storage endpoint refuses a body that exceeds it -- an understated size fails the PUT rather than the reservation. */
            size_bytes: number;
            /** @description SHA-256 of the bytes, hex. Optional, and worth sending: when we already hold this exact content the response says `skip_upload` and there is nothing to transfer. */
            content_hash?: string;
            /** @description Optional metadata recorded on the video. */
            duration_sec?: number;
            /** @description Optional metadata recorded on the video. */
            width?: number;
            /** @description Optional metadata recorded on the video. */
            height?: number;
        };
        VideoReservation: {
            /** @description Reference this as the evaluation's `video.upload_id`, once the video reaches `ready`. */
            video_id: string;
            /**
             * Format: uri
             * @description Where the bytes will be readable once the upload completes.
             */
            cdn_url: string;
            /** @description Where to PUT the bytes. A path or absolute URL on separate storage infrastructure, valid for 15 minutes, carrying its own signed grant -- send no `Authorization` header with it. Absent when `skip_upload` is true. */
            upload_path?: string;
            /** @description Present and true when `content_hash` matched content we already hold. Skip straight to referencing `video_id`: there is nothing to upload and no completion call to make. */
            skip_upload?: boolean;
        };
        Video: {
            id: string;
            /** @constant */
            object?: "video";
            status: components["schemas"]["VideoStatus"];
            /** Format: uri */
            cdn_url: string;
            duration_sec?: number | null;
            width?: number | null;
            height?: number | null;
            size_bytes?: number | null;
            /** @description Unix seconds. */
            created?: number;
        };
        VideoUrlRef: {
            /**
             * Format: uri
             * @description Public HTTP or HTTPS URL for an MP4 video.
             */
            url: string;
        };
        VideoBase64Ref: {
            /**
             * @description Base64-encoded MP4 bytes, sent inline with the request.
             *     Bounded by the 2 MB request body limit, not by the 50 MB file limit: base64 costs a third more than the bytes it carries, so the largest clip that fits inline is roughly 1.5 MB. That is well under a typical 15-second render. Use `url` for anything larger -- a body over the limit is rejected with 413, which is a transport failure rather than a validation one and so is not in this endpoint's error list.
             */
            b64_json: string;
        };
        VideoUploadRef: {
            /** @description The `video_id` of a video you uploaded and whose status has reached `ready`. See `POST /v1/videos`. */
            upload_id: string;
        };
        /**
         * @description How to give us the video. Exactly one of the three, and the choice is mostly about size.
         *     `upload_id` is the general answer: upload the file first (three calls, one of them straight to storage -- see `POST /v1/videos`) and reference it here. It is the only option that both reaches the 50 MB file limit and keeps the video private to your account.
         *     `url` is the shortcut when the video is already hosted somewhere we can GET. Note that it has to be publicly reachable; we send no credentials.
         *     `b64_json` sends the bytes inline. Convenient for a small local file, but bounded by the request body limit rather than the file limit -- see `POST /v1/evaluations`.
         */
        VideoRef: components["schemas"]["VideoUrlRef"] | components["schemas"]["VideoUploadRef"] | components["schemas"]["VideoBase64Ref"];
        /**
         * @example {
         *       "model": "galileo",
         *       "prompt": "A red ball rolls off a table and bounces twice.",
         *       "video": {
         *         "url": "https://cdn.example.com/red-ball.mp4"
         *       },
         *       "metadata": {
         *         "run_id": "render-123"
         *       }
         *     }
         */
        EvaluationCreate: {
            model?: components["schemas"]["ModelId"];
            /** @description Concrete model version to run. The deployment default applies when omitted. */
            model_version?: string;
            /**
             * @description Required when prompt-misalignment detection runs.
             * @default
             */
            prompt: string;
            video: components["schemas"]["VideoRef"];
            /**
             * @default [
             *       "visual_glitch",
             *       "prompt_misalignment"
             *     ]
             */
            glitch_types: components["schemas"]["GlitchType"][];
            /** @description JSON metadata echoed on the evaluation. Serialized size must not exceed 8192 bytes. */
            metadata?: {
                [key: string]: unknown;
            };
        };
        TimePoint: {
            frame: number;
            sec: number;
            timecode: string;
        };
        BoundingBox: {
            xmin: number;
            ymin: number;
            xmax: number;
            ymax: number;
        };
        BoxKeyframe: {
            frame: number;
            sec: number;
            box: components["schemas"]["BoundingBox"];
        };
        GlitchRegion: {
            start: components["schemas"]["TimePoint"];
            end: components["schemas"]["TimePoint"];
            boxes: components["schemas"]["BoxKeyframe"][];
        };
        PromptSegment: {
            text: string;
            char_start: number;
            char_end: number;
        };
        Glitch: {
            id: string;
            type: components["schemas"]["GlitchType"];
            description: string;
            prompt_segment?: components["schemas"]["PromptSegment"];
            region?: components["schemas"]["GlitchRegion"];
            /**
             * @description Who produced this finding. Absent means the model, which is the common case -- the field is only set explicitly where a human annotated something the model missed, so treat its absence as `model` rather than as unknown.
             *     Deliberately NOT declared with a `default`. A default reads to a code generator as "the server always sends this", and it does not: the value is omitted, not defaulted, and a generated type that made it required would be wrong on almost every finding.
             * @enum {string}
             */
            source?: "model" | "human";
            /**
             * @description How far a prompt requirement was from being realized: `6 - score`, so 1 is a minor mismatch and 5 means the requirement is absent entirely. This is also the number the reporting threshold reads, so a finding you receive is by definition one that cleared it.
             *     In practice this is a `prompt_misalignment` field. The visual detector does not score its findings, so a `visual_glitch` normally has no `severity` at all; where one does appear it came from an older pipeline and grades the defect rather than a requirement. Either way it is optional — branch on `type` and handle its absence rather than assuming a default.
             */
            severity?: number;
        };
        EvaluationSummary: {
            num_glitches: number;
            has_visual_glitch: boolean;
            has_prompt_misalignment: boolean;
        };
        VideoInfo: {
            duration_sec: number;
            width: number;
            height: number;
            fps: number;
            num_frames: number;
        };
        EvaluationUsage: {
            video_seconds: number;
            billable_units: number;
        };
        DetectorError: {
            code: string;
            message: string;
        };
        DetectorState: {
            detector: components["schemas"]["GlitchType"];
            status: components["schemas"]["DetectorStatus"];
            error?: components["schemas"]["DetectorError"];
        };
        EvaluationResult: {
            glitches: components["schemas"]["Glitch"][];
            summary: components["schemas"]["EvaluationSummary"];
        };
        EvaluationFailure: {
            type: string;
            code: string;
            message: string;
            request_id: string;
        };
        Evaluation: {
            /** Format: uuid */
            id: string;
            /** @constant */
            object: "evaluation";
            model: components["schemas"]["ModelId"];
            model_version: string;
            output_schema_version: string;
            /** @description Unix timestamp in seconds. */
            created: number;
            status: components["schemas"]["EvaluationStatus"];
            input: {
                prompt: string;
                video: components["schemas"]["VideoInfo"];
            };
            usage: components["schemas"]["EvaluationUsage"];
            result: components["schemas"]["EvaluationResult"] | null;
            error: components["schemas"]["EvaluationFailure"] | null;
            /** @description Per-detector state. Older evaluations may omit this field. */
            detectors?: components["schemas"]["DetectorState"][];
            /** @description Stored video identifier when the evaluation used an uploaded video. */
            video_id?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
        };
        EvaluationList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Evaluation"][];
        };
        RateLimitWindow: {
            limit: number;
            used: number;
            remaining: number;
            reset_at: number | null;
            reset_in_sec: number | null;
            window_sec: number;
            unlimited: boolean;
        };
        QuotaScopes: {
            detect: components["schemas"]["RateLimitWindow"];
            generate: components["schemas"]["RateLimitWindow"];
            upload: components["schemas"]["RateLimitWindow"];
        };
        QuotaReport: components["schemas"]["RateLimitWindow"] & {
            scopes: components["schemas"]["QuotaScopes"];
        };
        AccountLimits: {
            requests_per_min: number;
            window_sec: number;
            max_concurrent_jobs: number;
            rate_limits: {
                detect: components["schemas"]["RateLimitDefinition"];
                generate: components["schemas"]["RateLimitDefinition"];
                upload: components["schemas"]["RateLimitDefinition"];
            };
        };
        RateLimitDefinition: {
            max: number;
            window_sec: number;
        };
        ApiKeySummary: {
            name: string;
            prefix: string;
            last4: string;
        };
        Account: {
            /** @constant */
            object: "user";
            id: string | null;
            /** Format: email */
            email: string | null;
            name: string | null;
            tier: string;
            credits: number;
            unlimited: boolean;
            limits: components["schemas"]["AccountLimits"];
            api_key?: components["schemas"]["ApiKeySummary"];
        };
        ModelBuild: {
            id: components["schemas"]["ModelId"];
            label: string;
            version: string;
            note?: string;
        };
        Model: {
            id: components["schemas"]["ModelId"];
            /** @constant */
            object: "model";
            version: string;
            detectors: components["schemas"]["GlitchType"][];
            input: {
                formats: string[];
                max_duration_sec: number;
                max_file_bytes: number;
                aspect_ratios: string[];
            };
        };
        ModelList: {
            /** @constant */
            object: "list";
            builds: components["schemas"]["ModelBuild"][];
            default_build: string;
            data: components["schemas"]["Model"][];
        };
        PricingRates: {
            per_second_per_detector: number;
            per_second_by_detector?: {
                visual_glitch?: number;
                prompt_misalignment?: number;
            };
            cache_hit_rate: number;
            minimum: number;
            assumed_duration_sec: number;
            generation_from_catalog?: boolean;
        };
        Credits: {
            credits: number;
            pricing: components["schemas"]["PricingRates"];
            unlimited: boolean;
            per_generated_sec: number;
        };
        /** @enum {string} */
        ComponentState: "operational" | "degraded" | "down" | "unknown";
        ComponentStatus: {
            key: string;
            name: string;
            description: string;
            state: components["schemas"]["ComponentState"];
            detail: string;
            latency_ms: number | null;
        };
        SystemStatus: {
            state: components["schemas"]["ComponentState"];
            checked_at: number;
            components: components["schemas"]["ComponentStatus"][];
        };
        /** @enum {string} */
        ErrorType: "invalid_request_error" | "authentication_error" | "rate_limit_error" | "api_error";
        /** @enum {string} */
        ErrorCode: "invalid_body" | "unknown_model" | "missing_video" | "missing_prompt" | "prompt_too_long" | "invalid_glitch_types" | "video_too_long" | "invalid_video" | "not_found" | "not_implemented" | "insufficient_credits" | "missing_api_key" | "invalid_api_key" | "unauthenticated" | "rate_limited" | "concurrency_limit" | "internal_error" | "model_unavailable" | "model_output_invalid" | "model_timeout" | "run_abandoned";
        Error: {
            type: components["schemas"]["ErrorType"];
            code: components["schemas"]["ErrorCode"];
            message: string;
            request_id: string;
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
            quota?: components["schemas"]["RateLimitWindow"];
        };
    };
    responses: {
        /** @description The request cannot be processed as sent. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The API key is missing, invalid, or revoked. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The account balance cannot cover this evaluation. */
        InsufficientCredits: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The resource does not exist or is unavailable to this account. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The account reached a rate or concurrency limit. */
        RateLimited: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                "Retry-After": components["headers"]["RetryAfter"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The API encountered an unexpected error. */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A model service failed or returned an unusable response. */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A model run exceeded its deadline. */
        GatewayTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description This deployment does not implement the requested operation. */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Video identifier, as returned by `POST /v1/videos`. */
        VideoId: string;
        /** @description Evaluation identifier. */
        EvaluationId: string;
    };
    requestBodies: never;
    headers: {
        /** @description Maximum submissions in the current sliding window. */
        RateLimitLimit: number;
        /** @description Submissions available before the next refusal. */
        RateLimitRemaining: number;
        /** @description Unix seconds when the next rate-limit slot becomes available. */
        RateLimitReset: number;
        /** @description Seconds to wait before retrying. */
        RetryAfter: number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current platform status. */
            200: {
                headers: {
                    /** @description Public cache policy for this status snapshot. */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available models and builds. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current quota state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaReport"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credit balance and pricing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credits"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listEvaluations: {
        parameters: {
            query?: {
                /** @description Maximum evaluations to return. */
                limit?: number;
                /** @description Return evaluations for one stored video. */
                video_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
            501: components["responses"]["NotImplemented"];
        };
    };
    createEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationCreate"];
            };
        };
        responses: {
            /** @description Evaluation created. */
            201: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["RateLimitLimit"];
                    "X-RateLimit-Remaining": components["headers"]["RateLimitRemaining"];
                    "X-RateLimit-Reset": components["headers"]["RateLimitReset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            402: components["responses"]["InsufficientCredits"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
            502: components["responses"]["BadGateway"];
            504: components["responses"]["GatewayTimeout"];
        };
    };
    retrieveEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Evaluation identifier. */
                evaluation_id: components["parameters"]["EvaluationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Evaluation identifier. */
                evaluation_id: components["parameters"]["EvaluationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluation deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createVideo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoCreate"];
            };
        };
        responses: {
            /** @description Upload reserved, or an existing copy matched. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoReservation"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
        };
    };
    completeVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Video identifier, as returned by `POST /v1/videos`. */
                video_id: components["parameters"]["VideoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Upload accepted for validation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalServerError"];
        };
    };
    retrieveVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Video identifier, as returned by `POST /v1/videos`. */
                video_id: components["parameters"]["VideoId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Video found. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
